In [109]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [110]:
pwd


'/home/harish/dataPreprocessing'

In [111]:
cd ~/MachineLearning_LCO/


/home/harish/MachineLearning_LCO


In [112]:
ls

sairam.py


In [113]:
cd ~/dataPreprocessing/

/home/harish/dataPreprocessing


In [114]:
pwd

'/home/harish/dataPreprocessing'

In [115]:
df = pd.read_csv("/home/harish/Machine_learning/MachineLearning/DataSets/CleanupData.csv")

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   State             10 non-null     object 
 1   Age               9 non-null      float64
 2   Pocket Money      9 non-null      float64
 3   Course Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [117]:
df.head()

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes

In [118]:
df

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [119]:
# as we can see here the state, age and Pocket money are independent variables/Matrix: common convention to us upper case
# and course purchased is our focus to predict and dependant variable/Matrix : common convention to use lower case
X = df.iloc[:, :-1]


In [120]:
# gives a DF, but we want a matrix
X

State   Age  Pocket Money
0     Delhi  34.0        7200.0
1    Mumbai  17.0        4800.0
2  Banglore  20.0        5400.0
3    Mumbai  28.0        6100.0
4  Banglore  30.0           NaN
5     Delhi  25.0        5800.0
6    Mumbai   NaN        5200.0
7     Delhi  38.0        7900.0
8  Banglore  40.0        8300.0
9     Delhi  27.0        6700.0

In [121]:
X = df.iloc[:, :-1].values

In [122]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [123]:
y = df.iloc[:,3].values

In [124]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [125]:
# how to handle null/NaN values in dataset
from sklearn.impute import SimpleImputer
simpleImp = SimpleImputer(missing_values=np.nan,
    strategy='mean')
X[:,1:]

array([[34.0, 7200.0],
       [17.0, 4800.0],
       [20.0, 5400.0],
       [28.0, 6100.0],
       [30.0, nan],
       [25.0, 5800.0],
       [nan, 5200.0],
       [38.0, 7900.0],
       [40.0, 8300.0],
       [27.0, 6700.0]], dtype=object)

In [126]:
simpleImp.fit(X[:,1:3])

SimpleImputer()

In [127]:
X[:, 1:] = simpleImp.transform(X[:,1:])

In [128]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, 6377.777777777777],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', 28.77777777777778, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [129]:
y 

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [130]:
# handle categorical data in our data
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
X[:,0] = labelEncoder.fit_transform(X[:,0])

In [131]:
X

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

In [132]:
# create dummy matrix
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("state",OneHotEncoder(),[0])], remainder="passthrough") 
np.set_printoptions(suppress=True)
X = ct.fit_transform(X)


In [134]:
X

array([[0.0, 1.0, 0.0, 34.0, 7200.0],
       [0.0, 0.0, 1.0, 17.0, 4800.0],
       [1.0, 0.0, 0.0, 20.0, 5400.0],
       [0.0, 0.0, 1.0, 28.0, 6100.0],
       [1.0, 0.0, 0.0, 30.0, 6377.777777777777],
       [0.0, 1.0, 0.0, 25.0, 5800.0],
       [0.0, 0.0, 1.0, 28.77777777777778, 5200.0],
       [0.0, 1.0, 0.0, 38.0, 7900.0],
       [1.0, 0.0, 0.0, 40.0, 8300.0],
       [0.0, 1.0, 0.0, 27.0, 6700.0]], dtype=object)