In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pwd


'/home/harish/dataPreprocessing'

In [4]:
cd ~/MachineLearning_LCO/


/home/harish/MachineLearning_LCO


In [5]:
ls

sairam.py


In [6]:
cd ~/dataPreprocessing/

/home/harish/dataPreprocessing


In [7]:
pwd

'/home/harish/dataPreprocessing'

In [8]:
df = pd.read_csv("/home/harish/Machine_learning/MachineLearning/DataSets/CleanupData.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   State             10 non-null     object 
 1   Age               9 non-null      float64
 2   Pocket Money      9 non-null      float64
 3   Course Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [10]:
df.head()

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes

In [11]:
df

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [12]:
# as we can see here the state, age and Pocket money are independent variables/Matrix: common convention to us upper case
# and course purchased is our focus to predict and dependant variable/Matrix : common convention to use lower case
X = df.iloc[:, :-1]


In [13]:
# gives a DF, but we want a matrix
X

State   Age  Pocket Money
0     Delhi  34.0        7200.0
1    Mumbai  17.0        4800.0
2  Banglore  20.0        5400.0
3    Mumbai  28.0        6100.0
4  Banglore  30.0           NaN
5     Delhi  25.0        5800.0
6    Mumbai   NaN        5200.0
7     Delhi  38.0        7900.0
8  Banglore  40.0        8300.0
9     Delhi  27.0        6700.0

In [14]:
X = df.iloc[:, :-1].values

In [15]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [16]:
y = df.iloc[:,3].values

In [17]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [18]:
# how to handle null/NaN values in dataset
from sklearn.impute import SimpleImputer
simpleImp = SimpleImputer(missing_values=np.nan,
    strategy='mean')
X[:,1:]

array([[34.0, 7200.0],
       [17.0, 4800.0],
       [20.0, 5400.0],
       [28.0, 6100.0],
       [30.0, nan],
       [25.0, 5800.0],
       [nan, 5200.0],
       [38.0, 7900.0],
       [40.0, 8300.0],
       [27.0, 6700.0]], dtype=object)

In [19]:
simpleImp.fit(X[:,1:3])

SimpleImputer()

In [20]:
X[:, 1:] = simpleImp.transform(X[:,1:])

In [21]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, 6377.777777777777],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', 28.77777777777778, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [22]:
y 

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [23]:
# handle categorical data in our data
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
X[:,0] = labelEncoder.fit_transform(X[:,0])

In [24]:
X

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

In [25]:
# create dummy matrix
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("state",OneHotEncoder(),[0])], remainder="passthrough") 
np.set_printoptions(suppress=True)
X = ct.fit_transform(X)


In [26]:
X

array([[0.0, 1.0, 0.0, 34.0, 7200.0],
       [0.0, 0.0, 1.0, 17.0, 4800.0],
       [1.0, 0.0, 0.0, 20.0, 5400.0],
       [0.0, 0.0, 1.0, 28.0, 6100.0],
       [1.0, 0.0, 0.0, 30.0, 6377.777777777777],
       [0.0, 1.0, 0.0, 25.0, 5800.0],
       [0.0, 0.0, 1.0, 28.77777777777778, 5200.0],
       [0.0, 1.0, 0.0, 38.0, 7900.0],
       [1.0, 0.0, 0.0, 40.0, 8300.0],
       [0.0, 1.0, 0.0, 27.0, 6700.0]], dtype=object)

In [27]:
# handle y matrix for categorical data
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [28]:
y = labelEncoder.fit_transform(y)

In [29]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
# prepare test and training data set
# Split our data into two parts, one for training and one for testing

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8)

In [31]:
X_train


array([[1.0, 0.0, 0.0, 20.0, 5400.0],
       [0.0, 1.0, 0.0, 34.0, 7200.0],
       [0.0, 0.0, 1.0, 28.77777777777778, 5200.0],
       [0.0, 0.0, 1.0, 28.0, 6100.0],
       [0.0, 1.0, 0.0, 38.0, 7900.0],
       [1.0, 0.0, 0.0, 40.0, 8300.0],
       [0.0, 1.0, 0.0, 27.0, 6700.0],
       [0.0, 1.0, 0.0, 25.0, 5800.0]], dtype=object)

In [32]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 1])

In [34]:
# feature scaling
# Standard deviation or normalization
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
X_train = standardScaler.fit_transform(X_train) 
X_test = standardScaler.transform(X_test)

In [35]:
X_train

array([[ 1.73205081, -1.        , -0.57735027, -1.5979643 , -1.09361488],
       [-0.57735027,  1.        , -0.57735027,  0.61764507,  0.58171004],
       [-0.57735027, -1.        ,  1.73205081, -0.20881239, -1.27976209],
       [-0.57735027, -1.        ,  1.73205081, -0.3319018 , -0.44209963],
       [-0.57735027,  1.        , -0.57735027,  1.25067632,  1.23322529],
       [ 1.73205081, -1.        , -0.57735027,  1.56719195,  1.60551972],
       [-0.57735027,  1.        , -0.57735027, -0.49015961,  0.11634201],
       [-0.57735027,  1.        , -0.57735027, -0.80667524, -0.72132045]])

In [36]:
X_test

array([[   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778]])

In [47]:
a,b,c = [1,2,3]

In [42]:
a

1

In [44]:
b

2

In [45]:
c

3